
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[441] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   90,    9,   89,    9,    9,    9,    9,    9,
       49,   49,   49,   49,   49,   49,   49,   49,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   14,   13,   14,
       14,   14,   14,   14,   85,   85,   85,   85,   89,   89,
       89,   54,   53,   54,   54,   51,   72,   71,   72,   72,

       69,   62,   61,   62,   62,   60,   67,   66,   67,   67,
       64,   83,   83,   83,   83,   83,   58,   58,   58,   56,
       57,   76,   76,   76,   76,   75,    6,    6,    6,    6,
        4,   18,   18,   18,   16,   22,   22,   22,   20,   89,
       31,   31,   28,   31,   31,   27,   40,   40,   39,   40,
       40,   40,   38,   37,   33,   89,   43,   43,   43,   43,
       41,   48,   48,   48,   48,   44,   48,   45,    7,    0,
        8,    0,   84,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,    0,    0,   51,   70,   69,
       60,   65,   64,    0,    0,    0,    0,    0,   56,    0,

        0,   75,    0,    0,    4,    0,   16,    0,   20,    0,
        0,    0,   27,    0,    0,   38,   32,    0,   41,    0,
       44,   46,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   86,   52,    0,    0,
        0,   77,    0,    0,    0,    0,    0,    0,    0,    0,
       24,   29,    0,   35,    0,    0,    0,    0,   87,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   78,   81,    0,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    0,    0,   42,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   80,   82,    0,    0,   17,   21,    0,    0,
        0,    0,    0,    0,    0,   25,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   79,   74,    0,    0,
       34,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       73,    0,    0,    0,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   30,   36,   47,    0,    0,    1,    0,    0,
        0,    2,    0,    0,    0,    0,   55,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   15,    0,    0,

       50,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   10,    0,
        0,    0,   63,    0,    0,    0,   19,   23,   59,    0,
        0,   68,    0,    0,    0,    0,    0,    0,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    5,    6,    1,    7,
        8,    9,    1,   10,   11,    1,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    1,
       16,   17,    1,    1,   18,   13,   13,   19,   13,   13,
       20,   13,   13,   13,   13,   13,   13,   13,   13,   21,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   22,    1,   23,   24,   25,   13,

       26,   27,   13,   28,   29,   13,   30,   31,   32,   33,
       34,   35,   13,   36,   37,   38,   39,   40,   41,   13,
       42,   13,   43,   44,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    1,    4,    4,    4,
        4,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[468] =
    {   0,
        0,    6,   45,   84,  123,  162,   12,   18,   19,   24,
       17,   26,   27,   29,   36,   37,   42,   43,  202,    0,
      247,    0,  292,    0,  337,    0,  382,    0,  427,    0,
       48,   51,  472,    0,  517,    0,  562,    0,  607,    0,
      652,    0,  697,    0,  742,    0,   58,   61,  787,    0,
      832,    0, 1129, 1130, 1125, 1113, 1122, 1121, 1115, 1100,
     1130,    0, 1118, 1112, 1089, 1085, 1080, 1094, 1130,    0,
     1112, 1106, 1083, 1084, 1079, 1073, 1087, 1130, 1130, 1095,
     1104, 1103, 1097, 1082, 1130, 1100, 1091, 1093, 1130, 1097,
     1091, 1130, 1130, 1095, 1089, 1093, 1130, 1130, 1092, 1086,

     1090, 1130, 1130, 1089, 1083,    0, 1130, 1130, 1087, 1081,
     1085, 1130, 1084, 1078,   70,   71, 1130, 1082, 1076,    0,
     1130, 1130, 1076, 1079, 1073, 1077, 1130, 1035, 1075, 1069,
     1073, 1130, 1072, 1066, 1070, 1130, 1069, 1063, 1067, 1066,
     1130, 1054, 1130, 1064, 1058,    0, 1130,    0, 1130, 1051,
     1061, 1055,    0,    0, 1130,    0, 1130, 1052, 1058, 1052,
        0, 1130, 1045, 1055, 1049,    0, 1054, 1130, 1130, 1042,
     1130, 1040, 1130, 1018,   83, 1018, 1019, 1028, 1014, 1045,
     1013, 1014, 1017, 1022, 1130, 1041,  998, 1038, 1130, 1037,
        0, 1130, 1036,   76,    0, 1035,   89,   86,    0, 1034,

     1026, 1032, 1031, 1020, 1029,  987, 1027,  985, 1025, 1013,
     1023, 1023,    0,   96, 1022,    0,    0, 1007,    0, 1020,
        0, 1130, 1006, 1006,  991, 1008,    0,  990,  979,  980,
      986, 1003,  985,  989,  973,   46, 1130, 1130, 1006, 1006,
     1004, 1130,   93,  990,  991,  988,  989,  989,  998,  997,
     1130,  992,  988, 1130,  990,  993,  988,  991, 1130,  971,
      976,    0,  969,  965,  952,  966,  971,  964,  955,  956,
      954,  957, 1130, 1130,  971,  964,  976,  976,  974, 1130,
      961,  961,  960,  970,  956,  968, 1130,  967,   22,  946,
      965,  944,  931,  944,  941,  960,  939,  940,  938,  938,

      922,  954, 1130, 1130,  950,  952, 1130, 1130,  940,  950,
      938,  937,  915,  911,  918, 1130,  922,  915,  909,  914,
      937,  917,  905,  910,  917,  935, 1130, 1130,  895,  922,
     1130,  921,  920,  911,  896,  906,  893,  901,  887,  901,
     1130,  886,  883,  896,  884,  895, 1130,  903,  900,  198,
      168,  170,  193,  192,  162,  162,  189,  188,  167,  151,
      152,  172, 1130, 1130, 1130,  152,  164, 1130,  168,  158,
      156, 1130,  165,  140,  139,  148, 1130,  152,  139,  158,
      140,  135,  154,  141,  143,  142,  126,  120,  155,  121,
      126,  152,  118,  116,  129,  147,  116, 1130,  144,  143,

     1130,  141,  118,  117,  135,  123,  126,  125,  124,  133,
       98,  131,   94,  118,  116,  115,  114,  123, 1130,   88,
      119,  118, 1130,  106,  105,   84, 1130, 1130, 1130,  102,
       83, 1130,   91,   75,   89,  107,  103,  106, 1130, 1130,
      877,  881,  885,  889,  893,  897,  102,   99,  900,  903,
       90,  906,  909,   86,  912,  915,  918,  921,  924,   79,
       75,   68,   57,   15,    9,    3,    2
    } ;

static const flex_int16_t yy_def[468] =
    {   0,
      441,  441,  442,  442,  443,  443,  444,  444,  445,  445,
      446,  446,  446,  446,  446,  446,  446,  446,  440,   19,
      440,   21,  440,   23,  440,   25,  440,   27,  440,   29,
      446,  446,  440,   33,  440,   35,  440,   37,  440,   39,
      440,   41,  440,   43,  440,   45,  446,  446,  440,   49,
      440,   51,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  447,  440,  440,  440,  440,  440,  440,  440,  448,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  449,  440,  440,  440,  440,

      450,  440,  440,  440,  440,  451,  440,  440,  440,  440,
      452,  440,  440,  440,  453,  453,  440,  440,  440,  454,
      440,  440,  440,  440,  440,  455,  440,  440,  440,  440,
      456,  440,  440,  440,  457,  440,  440,  440,  458,  459,
      440,  440,  440,  440,  440,  460,  440,  461,  440,  440,
      440,  440,  462,  462,  440,  463,  440,  440,  440,  440,
      464,  440,  440,  440,  440,  465,  440,  440,  440,  440,
      440,  440,  440,  440,  447,  440,  440,  440,  440,  448,
      440,  440,  440,  440,  440,  440,  440,  449,  440,  450,
      451,  440,  452,  440,  466,  440,  453,  440,  454,  440,

      440,  455,  440,  440,  456,  440,  457,  440,  458,  440,
      459,  440,  460,  461,  440,  462,  463,  440,  464,  440,
      465,  440,  440,  440,  440,  440,  467,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      466,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  467,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,    0,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440
    } ;

static const flex_int16_t yy_nxt[1176] =
    {   0,
      440,  440,   55,   56,   57,  262,  241,   58,   55,   56,
       57,   59,  221,   58,   79,   80,   81,   59,  219,   82,
       79,   80,   81,   83,   90,   82,   86,   87,   91,   83,
       88,   86,   87,   90,   90,   88,   90,   91,   91,   60,
       91,  313,  314,   90,   90,   60,   62,   91,   91,   90,
       90,   84,   63,   91,   91,   90,   64,   84,   90,   91,
      217,  155,   91,  156,  155,   90,  156,   65,   90,   91,
      271,  216,   91,  194,  198,  195,  195,   66,  214,  196,
      196,   67,  213,  272,   68,   62,  226,  239,  227,  199,
      240,   63,  243,  191,  195,   64,  244,  239,  196,  253,

      240,  254,  180,  276,  239,  175,   65,  240,  439,  438,
      437,  436,  435,  434,  433,  432,   66,  431,  430,  429,
       67,  428,  427,   68,   70,  426,  425,  424,  423,  422,
       71,  421,  420,  419,   72,  418,  417,  416,  415,  414,
      413,  412,  411,  410,  409,   73,  408,  407,  406,   74,
      405,   75,  404,  403,  402,  401,  400,  399,  398,   76,
      397,  396,   77,   70,  395,  394,  393,  392,  391,   71,
      390,  389,  388,   72,  387,  386,  385,  384,  383,  382,
      381,  380,  379,  378,   73,  377,  376,  375,   74,  374,
       75,  373,  372,  371,  370,  369,  368,  367,   76,  366,

      365,   77,   92,   92,   93,   92,   92,   92,   92,   94,
       92,   92,   92,   95,   96,   92,   92,   92,   92,   96,
       96,   96,   96,   92,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   92,   92,   92,   97,   97,   98,
       97,   97,   97,   97,   99,   97,   97,   97,  100,  101,
       97,   97,   97,   97,  101,  101,  101,  101,   97,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,   97,
       97,   97,  102,  102,  103,  102,  102,  102,  102,  104,

      102,  102,  102,  105,  106,  102,  102,  102,  102,  106,
      106,  106,  106,  102,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  102,  102,  102,  107,  107,  108,
      107,  107,  107,  107,  109,  107,  107,  107,  110,  111,
      107,  107,  107,  107,  111,  111,  111,  111,  107,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  107,
      107,  107,  112,  112,  112,  112,  112,  112,  112,  113,
      112,  112,  112,  114,  115,  112,  112,  112,  112,  115,

      115,  115,  115,  112,  115,  115,  115,  116,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  112,  112,  112,  117,  117,  117,
      117,  117,  117,  117,  118,  117,  117,  117,  119,  120,
      117,  121,  117,  117,  120,  120,  120,  120,  117,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  117,
      117,  117,  122,  123,  122,  122,  122,  122,  122,  124,
      122,  122,  122,  125,  126,  122,  122,  122,  122,  126,
      126,  126,  126,  122,  126,  126,  126,  126,  126,  126,

      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  122,  122,  122,  127,  127,  127,
      128,  127,  127,  127,  129,  127,  127,  127,  130,  131,
      127,  127,  127,  127,  131,  131,  131,  131,  127,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  127,
      127,  127,  132,  132,   89,  132,  132,  132,  132,  133,
      132,  132,  132,  134,  135,  132,  132,  132,  132,  135,
      135,  135,  135,  132,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,

      135,  135,  135,  135,  132,  132,  132,  136,  136,   89,
      136,  136,  136,  136,  137,  136,  136,  136,  138,  139,
      136,  136,  136,  136,  139,  139,  139,  139,  136,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  136,
      136,  136,   89,   89,   89,   89,   89,   89,   89,   90,
       89,   89,   89,   91,  140,   89,   89,   89,   89,  140,
      140,  140,  140,   89,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,   89,   89,   89,  141,  141,  141,

      142,  141,  143,  141,  144,  141,  141,  141,  145,  146,
      141,  141,  141,  141,  146,  146,  146,  146,  141,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  141,
      141,  141,  147,  148,  149,  150,  147,  147,  147,  151,
      147,  147,  147,  152,  153,  147,  147,  147,  147,  153,
      153,  153,  153,  147,  153,  153,  153,  154,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  147,  147,  147,  157,  157,   89,
      158,  157,  157,  157,  159,  157,  157,  157,  160,  161,

      157,  157,  157,  157,  161,  161,  161,  161,  157,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  157,
      157,  157,  162,  162,   89,  163,  162,  162,  162,  164,
      162,  162,  162,  165,  166,  162,  167,  162,  162,  166,
      166,  166,  166,  162,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  162,  168,  162,   54,   54,   54,
       54,   61,   61,   61,   61,   69,   69,   69,   69,   78,
       78,   78,   78,   85,   85,   85,   85,   89,   89,   89,

       89,  188,  364,  188,  190,  363,  190,  193,  362,  193,
      197,  197,  197,  202,  361,  202,  205,  360,  205,  207,
      359,  207,  209,  358,  209,  211,  357,  211,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  276,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,

      283,  282,  281,  280,  279,  278,  277,  275,  274,  273,
      270,  269,  268,  267,  266,  265,  264,  263,  261,  260,
      259,  258,  257,  256,  255,  252,  210,  251,  208,  250,
      206,  249,  204,  248,  247,  201,  246,  245,  242,  192,
      189,  187,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  225,  224,  223,  222,  173,  172,  220,
      173,  172,  218,  173,  172,  215,  173,  172,  212,  210,
      208,  173,  172,  206,  173,  172,  204,  173,  172,  203,
      201,  173,  172,  200,  173,  172,  173,  172,  192,  173,
      172,  173,  172,  189,  173,  172,  187,  173,  172,  173,

      172,  173,  186,  172,  174,  173,  172,  185,  170,  179,
      184,  183,  182,  181,  173,  172,  179,  178,  177,  176,
      173,  172,  174,  173,  172,  171,  170,  169,  440,   53,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440
    } ;

static const flex_int16_t yy_chk[1176] =
    {   0,
        0,    0,    1,    1,    1,  467,  466,    1,    2,    2,
        2,    1,  465,    2,    7,    7,    7,    2,  464,    7,
        8,    8,    8,    7,   11,    8,    9,    9,   11,    8,
        9,   10,   10,   12,   13,   10,   14,   12,   13,    1,
       14,  289,  289,   15,   16,    2,    3,   15,   16,   17,
       18,    7,    3,   17,   18,   31,    3,    8,   32,   31,
      463,   47,   32,   47,   48,   47,   48,    3,   48,   47,
      236,  462,   48,  115,  116,  115,  116,    3,  461,  115,
      116,    3,  460,  236,    3,    4,  175,  194,  175,  454,
      194,    4,  197,  451,  197,    4,  198,  198,  197,  214,

      198,  214,  448,  243,  243,  447,    4,  243,  438,  437,
      436,  435,  434,  433,  431,  430,    4,  426,  425,  424,
        4,  422,  421,    4,    5,  420,  418,  417,  416,  415,
        5,  414,  413,  412,    5,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,    5,  400,  399,  397,    5,
      396,    5,  395,  394,  393,  392,  391,  390,  389,    5,
      388,  387,    5,    6,  386,  385,  384,  383,  382,    6,
      381,  380,  379,    6,  378,  376,  375,  374,  373,  371,
      370,  369,  367,  366,    6,  362,  361,  360,    6,  359,
        6,  358,  357,  356,  355,  354,  353,  352,    6,  351,

      350,    6,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   37,   37,   37,   37,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,  441,  441,  441,
      441,  442,  442,  442,  442,  443,  443,  443,  443,  444,
      444,  444,  444,  445,  445,  445,  445,  446,  446,  446,

      446,  449,  349,  449,  450,  348,  450,  452,  346,  452,
      453,  453,  453,  455,  345,  455,  456,  344,  456,  457,
      343,  457,  458,  342,  458,  459,  340,  459,  339,  338,
      337,  336,  335,  334,  333,  332,  330,  329,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  315,  314,
      313,  312,  311,  310,  309,  306,  305,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      288,  286,  285,  284,  283,  282,  281,  279,  278,  277,
      276,  275,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  261,  260,  258,  257,  256,  255,  253,  252,

      250,  249,  248,  247,  246,  245,  244,  241,  240,  239,
      235,  234,  233,  232,  231,  230,  229,  228,  226,  225,
      224,  223,  220,  218,  215,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  196,  193,
      190,  188,  187,  186,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  174,  172,  170,  167,  165,  164,  163,
      160,  159,  158,  152,  151,  150,  145,  144,  142,  140,
      139,  138,  137,  135,  134,  133,  131,  130,  129,  128,
      126,  125,  124,  123,  119,  118,  114,  113,  111,  110,
      109,  105,  104,  101,  100,   99,   96,   95,   94,   91,

       90,   88,   87,   86,   84,   83,   82,   81,   80,   77,
       76,   75,   74,   73,   72,   71,   68,   67,   66,   65,
       64,   63,   60,   59,   58,   57,   56,   55,   53,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "program.l"
#line 2 "program.l"
	/*student: Horovei Andreea-Georgiana, 335CC*/
	#include<stdio.h>
	#include<string.h>
	#include<stdbool.h>
	
	#define MAX_VARIABLES 200 /*numarul maxim de variabile care pot aparea in fisierul de intrare*/
	
	int max_chars = 200;
	char* grammar = " ::= Grammar";
	char* automat = " ::= PushDownAutomata";
	char* stiva; /*retine ce trebuie pus pe stiva la o tranzitie*/
	char* stare; /*retine starea curenta pentru care se face scrierea unei tranzitii*/
	char* name;
	int afisare_tranzitii; /*are valoarea 1 daca s-a afisat deja mesajul "Functia de tranzitie: ", altfel este 0*/
	int counter = 0;
	int numarare_stari_as = 0;
	bool stari_finale = false; /*devine true daca exista stari finale in definitia unui AS*/
	bool afisare_automat = false; /*devine true daca la momentul curent este afisata definitia unui automat*/
	bool gramatica = false; /*devine true daca la momentul curent este afisata definit unei gramatici*/
	
	char* variabile[MAX_VARIABLES];
	int nr_variabile; /*retine dimensiunea pentru vectorul de variabile*/
	
	char* valori_variabile[MAX_VARIABLES][2]; /*memoreaza asocierile variabila-valoare gasite in fisier*/
	int nr_valori; /*retine numarul de asocieri valori-variabile identificate in cadrul analizei*/
	char* variabila_curenta; /*retine variabila curenta pentru care se memoreaza valorile*/
	
	
	/*aceleasi structuri pentru memorarea varibilelor sunt definite si pentru varibilele interne definitiei unui automat/gramatici*/
	/*aceste structuri sunt dezalocate la finalul definirii automatului/gramaticii curente*/
	char* variabile_interne[MAX_VARIABLES];
	int nr_variabile_interne; /*retine dimensiunea pentru vectorul de variabile interne definite in interiorul unei structuri*/
	
	char* valori_variabile_interne[MAX_VARIABLES][2]; /*memoreaza asocierile variabila - valoare gasite in defintia curenta*/
	int nr_valori_interne; /*retine numarul de asocieri valori-variabile identificate in cadrul analizei*/
	bool variabila_interna = false; /*devine true daca se face memorarea variabilei ca varibila interna*/

	char* variabila_tranzitie; /*retine valoarea unei variabile identificata in definitia unui AS/unei gramatici*/

	/*primeste un simbol si intoarce 1 daca simbolul respectiv este memorat ca variabila globala*/
	int verifica_variabila_globala(char* simbol) { 
		int i;
		for (i = 0; i < nr_variabile; i++) { 
			if (strcmp(simbol, variabile[i]) == 0) {
				return 1;
			}
		}
		return 0;
	} 
	
	/*primeste un simbol si intoarce 1 daca simbolul respectiv este memorat ca variabila locala*/
	int verifica_variabila_interna(char* simbol) { 
		int i;
		for (i = 0; i < nr_variabile_interne; i++) { 
			if (strcmp(simbol, variabile_interne[i]) == 0) {
				return 1;
			}
		}
		return 0;
	} 
	
	/*intoarce indicele primei aparitii a variabilei in vectorul de valori asociate variabilelor globale*/
	int prima_aparitie(char* simbol) {
		int i;
		for (i = 0; i < nr_valori; i++) {
			if (strcmp(valori_variabile[i][0], simbol) == 0) {
				return i;
			}
		}
		return -1;
	}
	
	/*intoarce indicele primei aparitii a variabilei in vectorul de valori asociate variabilelor locale definitiei curente*/
	int prima_aparitie_interna(char* simbol) {
		int i;
		for (i = 0; i < nr_valori; i++) {
			if (strcmp(valori_variabile_interne[i][0], simbol) == 0) {
				return i;
			}
		}
		return -1;
	}
	
	char* copie_tranzitie1; /*memoreaza o copie a tranzitiei pentru a face afisarea la explicitarea varibilelor*/
	char* copie_tranzitie2;
	
	bool varibila_interna; /*devine true daca variabila identificata in tranzitia curenta este variabila interna*/
	
	void free_variabile_locale() {
		int i;
		for (i = 0; i < nr_variabile_interne; i++) {
			free(variabile_interne[i]);
		}
		nr_variabile_interne = 0;
	}
	
	void free_valori_var_locale() {
		int i;
		for (i = 0; i < nr_valori_interne; i++) {
			free(valori_variabile_interne[i][0]);
			free(valori_variabile_interne[i][1]);
			valori_variabile_interne[i][0] = NULL;
			valori_variabile_interne[i][1] = NULL;
		}
		nr_valori_interne = 0;
	}
	
	/*variabile si functii pentru prelucrarea gramaticii si determinarea tipul acesteia*/
	char* neterminale[MAX_VARIABLES];
	int nr_neterminale;
	char* alfabet[MAX_VARIABLES];
	int nr_simb_alfabet; /*numarul de simboluri ale alfabetului*/
	char* simbol_start;
	
	/*intorce 1 daca simbol este neterminal, altfel intoarce -1*/
	int check_neterminal(char* simbol) {
		int i;
		for (i = 0; i <= nr_neterminale; i++) {
			if (strcmp(simbol, neterminale[i]) == 0) {
				return 1;
			}	
		}
		return -1;
	}
	
	/*intoarce 1 daca simbol este terminal, alfel intoarce -1*/
	int check_terminal(char* simbol) {
		int i;
		for (i = 0; i <= nr_simb_alfabet; i++) {
			if (strcmp(simbol, alfabet[i]) == 0) {
				return 1;
			}
		}
		return -1;
	}
	
	/*afisare alfabet gramatica*/
	void print_alfabet() {
		printf("Alfabetul gramaticii: {");
		int i;
		for (i = 0; i <= nr_simb_alfabet; i++) {
			if (i != nr_simb_alfabet) {
				printf("%s, ", alfabet[i]);
			}
			else {
				printf("%s}\n", alfabet[i]);
			}	
		}
		printf("\n");
	}
	
	/*elibereaza memoria alocata pentru a retine el. din alfabet, neterminalii, simb, de start*/
	void free_buffers() {
		int i;
		for (i = 0; i <= nr_neterminale; i++) {
			free(neterminale[i]);
			neterminale[i] = NULL;
		}
		nr_neterminale = 0;
		
		for (i = 0; i <= nr_simb_alfabet; i++) {
			free(alfabet[i]);
			alfabet[i] = NULL;
		}
		nr_simb_alfabet = 0;
	
	}
	
	/*retine numarul de simboluri din stanga si din dreapta productiei*/
	int st = 0;
	int dr = 0;
	
	bool tip_gasit_gfr = false; /*devine true daca a fost identificat si afisat tipul de gramatica (GFR)*/
	bool caz_special = false; /*este true daca a fost gasita tranzitia simbol_start->e*/
	bool exceptie_productie = false;/*este true cand productia curenta care se analizeaza are in partea stanga DOAR simbolul de start*/
	int check_start_symbol = 0; /*retine de cate ori apare simbolul de start in partea dreapta a unei productii pt GDC sau GFR*/
	
#line 1029 "lex.yy.c"

#line 218 "program.l"
	/*gramatica poate fi maxim de tipul 2*/
 

	/*gramatica poate fi maxim de tipul 1*/


#line 1038 "lex.yy.c"

#define INITIAL 0
#define GRAMATICA 1
#define AUTOMAT 2
#define GASESTE_NUME 3
#define COMENTARIU 4
#define ALFABET_GRAMATICA 5
#define NETERMINALI_GRAMATICA 6
#define SIMBOL_START_GRAMATICA 7
#define PRODUCTII_GRAMATICA 8
#define ALFABET_INTRARE_AS 9
#define ALFABET_STIVA 10
#define STARE_INITIALA_AS 11
#define STARI_FINALE_AS 12
#define TRANZITIE_AS 13
#define NUMARARE_STARI 14
#define STIVA 15
#define DEFINIRE_TRANZITII 16
#define MEMORARE_VARIABILE 17
#define MEMORARE_ALFABET_GRAMATICA 18
#define MEMORARE_NETERMINALI 19
#define MEMORARE_SIMBOL_START 20
#define TIP_2_3_GRAMATICA 21
#define TIP_2_1_GRAMATICA 22
#define VERIFICA_TIP_3 23
#define TIP_1_0_GRAMATICA_ST 24
#define TIP_1_0_GRAMATICA_DR 25

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 225 "program.l"

						  
	/*s-a gasit o variabila in starea INITIAL, se va memora ca variabila gloabal impreuna cu valorile asociate acesteia*/									  	
#line 1294 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 441 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1130 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 228 "program.l"
{ int before_variable_state = YYSTATE;
							          		  yy_push_state(before_variable_state);
							          		  BEGIN(MEMORARE_VARIABILE); }	
	YY_BREAK
/*s-a gasit o variabila intr-una dintre starile AUTOMAT/GRAMATICA, se va memora ca variabila interna*/									  	
case 2:
YY_RULE_SETUP
#line 232 "program.l"
{ int before_variable_state = YYSTATE;
							          		  yy_push_state(before_variable_state);
							          		  BEGIN(MEMORARE_VARIABILE);
							          		  variabila_interna = true; }							          		  
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 237 "program.l"
{ yyless(yyleng - strlen(" ::= {")); 
											  if (variabila_interna == true) { /*variabila gasita trebuie memorata ca variabila interna*/
											  	variabile_interne[nr_variabile_interne++] = strdup(yytext);
												variabila_curenta = strdup(yytext);
										      }
										      else { /*este memorata o valoare pentru o variabia globala*/
										      	variabile[nr_variabile++] = strdup(yytext);
												variabila_curenta = strdup(yytext);		
										      }
										    }		
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 248 "program.l"
{ if (variabila_interna == false) {
												  valori_variabile[nr_valori][0] = strdup(variabila_curenta);
												  valori_variabile[nr_valori][1] = strdup(yytext);
												  nr_valori++;
											  }
											  else {
												  valori_variabile_interne[nr_valori_interne][0] = strdup(variabila_curenta);
												  valori_variabile_interne[nr_valori_interne][1] = strdup(yytext);
												  nr_valori_interne++;
											  }
											}
	YY_BREAK
/*s-a identificat finalul definirii unei varibile*/									      	  
case 5:
YY_RULE_SETUP
#line 260 "program.l"
{ yy_pop_state(); variabila_interna = false; }					  
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 261 "program.l"
{ }				
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 267 "program.l"
{ BEGIN(GASESTE_NUME); }	
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 269 "program.l"
{ }	
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 270 "program.l"
{ yymore(); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 273 "program.l"
{ yyless(yyleng - strlen(" ::= Grammar (\n"));
										  	  printf("Numele gramaticii: %s\n", yytext); 
										  	  BEGIN(GRAMATICA); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 277 "program.l"
{ yyless(yyleng - strlen(" ::= PushDownAutomata (\n"));
										  	  		  printf("Numele automatului: %s\n", yytext); 
										  	  		  afisare_automat = true;
										  	  		  BEGIN(AUTOMAT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 281 "program.l"
{ }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 282 "program.l"
{ }
	YY_BREAK
/*oricare alte caractere analizata in aceasta stare alcatuiesc numele cautat si sunt memorate*/
case 14:
YY_RULE_SETUP
#line 284 "program.l"
{ yymore(); }
	YY_BREAK
/*incepe definitia alfabetului gramaticii*/
case 15:
YY_RULE_SETUP
#line 288 "program.l"
{ BEGIN(MEMORARE_ALFABET_GRAMATICA); }
	YY_BREAK
/*este memorat simbolul din alfabet continut in yytext*/
case 16:
YY_RULE_SETUP
#line 290 "program.l"
{ alfabet[nr_simb_alfabet++] = strdup(yytext);} 
	YY_BREAK
/*este identificat ultimul simbol din alfabet; s-a incheiat definitia alfebtului => se revine la starea GRAMATICA*/
case 17:
YY_RULE_SETUP
#line 292 "program.l"
{ yyless(yyleng - 4); alfabet[nr_simb_alfabet] = strdup(yytext); BEGIN(GRAMATICA); } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 293 "program.l"
{ }
	YY_BREAK
/*incepe definitia multimii neterminalelor*/
case 19:
YY_RULE_SETUP
#line 296 "program.l"
{ BEGIN(MEMORARE_NETERMINALI); }
	YY_BREAK
/*este memorat simbolul din alfabet continut in yytext*/
case 20:
YY_RULE_SETUP
#line 298 "program.l"
{ neterminale[nr_neterminale++] = strdup(yytext); } 
	YY_BREAK
/*este identificat ultimul neterminal; s-a incheiat definitia multimii neterminalelor => se revine la starea GRAMATICA*/
case 21:
YY_RULE_SETUP
#line 300 "program.l"
{ yyless(yyleng - 4); neterminale[nr_neterminale] = strdup(yytext); BEGIN(GRAMATICA); } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 301 "program.l"
{ }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 303 "program.l"
{ BEGIN(MEMORARE_SIMBOL_START); }
	YY_BREAK
/*este identificat simbolul de start*/
case 24:
YY_RULE_SETUP
#line 305 "program.l"
{ yyless(yyleng - 2); simbol_start = strdup(yytext); BEGIN(GRAMATICA); }
	YY_BREAK
/*este identificata o productie pt care in partea dreapta gasim un singur neterminal*/	
case 25:
YY_RULE_SETUP
#line 309 "program.l"
{ 
	/*presupunem ca avem GR sau GIC*/
	BEGIN(TIP_2_3_GRAMATICA);	
	/*este identificata prezenta simbolului de start in stanga unei productii*/
	yyless(yyleng - 4);
	if (strcmp(simbol_start, yytext + 1) == 0) {
		exceptie_productie = true;
	}
}
	YY_BREAK
/*daca in partea stanga a unei productii este gasit &, gramatica poate fi maxim GDC*/
case 26:
YY_RULE_SETUP
#line 319 "program.l"
{ st = 2; BEGIN(TIP_1_0_GRAMATICA_ST); }
	YY_BREAK
/*sunt identificate simbolurile din partea dreapta a productiei*/
case 27:
YY_RULE_SETUP
#line 321 "program.l"
{
	/*daca simbolul curent este neterminal*/
	if (check_neterminal(yytext) == 1) {
		yy_push_state(YYSTATE); /*salveaza starea curenta*/
		BEGIN(VERIFICA_TIP_3); /*verifica ce urmeaza dupa neterminalul curent*/
		if (strcmp(yytext, simbol_start) == 0 ) {
			/*incrementeaza numarul de aparitii ale simbolului de start in partea dreapta a unei productii*/
			check_start_symbol++;
		}
	}
	if (strcmp(yytext, "e") == 0) {
		if (exceptie_productie == true) {
			caz_special = true;
		}
	}
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 339 "program.l"
{ } 
	YY_BREAK
/*s-a terminat analiza productiei de pe linia curenta; la acest match stim ca productia tocmai analizata indica GR*/
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 341 "program.l"
{ BEGIN(GRAMATICA); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 342 "program.l"
{ printf("Tipul gramaticii: GR\n"); BEGIN(INITIAL); print_alfabet(); free_buffers(); exceptie_productie = false; caz_special = false; check_start_symbol = 0; }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 343 "program.l"
{ }
	YY_BREAK
/*daca dupa un neterminal avem alti neterminali sau terminali, gramatica nu poate fi GR*/
/*se trece in starea TIP_2_1_GRAMATICA unde se verifica partea stanga a productiilor pt a distinge intre GIC si GDC*/
case 32:
YY_RULE_SETUP
#line 347 "program.l"
{ if (strcmp(yytext, simbol_start) == 0) { check_start_symbol++; } BEGIN(TIP_2_1_GRAMATICA); }	
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 348 "program.l"
{ yyless(0); yy_pop_state(); }
	YY_BREAK
/*stare in care se ajunge dupa ce am identificat ca gramatica poate fi maxim de tip 2*/
/*verificam daca productiile pastreaza in partea stanga un singur neterminal*/
case 34:
YY_RULE_SETUP
#line 353 "program.l"
{ }
	YY_BREAK
/*daca este identificat simbol de concatenare in partea stanga a productiei, gramatica nu poate fi GIC*/
case 35:
YY_RULE_SETUP
#line 355 "program.l"
{ st = 1; BEGIN(TIP_1_0_GRAMATICA_ST); }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 356 "program.l"
{ printf("Tipul gramaticii: GIC\n"); BEGIN(INITIAL); print_alfabet(); free_buffers(); check_start_symbol = 0; exceptie_productie = false; caz_special = false; check_start_symbol = 0;}
	YY_BREAK
/*la identificarea lui e, este verificat daca apare tranzitia simbol_start->e*/
case 37:
YY_RULE_SETUP
#line 358 "program.l"
{ 
	if (exceptie_productie == true) {
		/*a fost identificata tranzitia S->e*/
		caz_special = true; 
	}
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 364 "program.l"
{
	if (strcmp(yytext, simbol_start) == 0) {
		check_start_symbol++;
	}
}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 369 "program.l"
{ }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 370 "program.l"
{ }
	YY_BREAK
/*sunt numarate simbolurile din partea stanga a productiei curente*/
case 41:
YY_RULE_SETUP
#line 375 "program.l"
{ st++; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 376 "program.l"
{ BEGIN(TIP_1_0_GRAMATICA_DR); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 377 "program.l"
{ }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 379 "program.l"
{ 
	if (strcmp(yytext, "e") != 0) {
		dr++; 
	}
	if (strcmp(simbol_start, yytext) == 0) {
		if (exceptie_productie == true) {
			check_start_symbol++;
		}
	}
}
	YY_BREAK
/*trebuie verificat st <= dr pt productia curenta*/
case 45:
YY_RULE_SETUP
#line 390 "program.l"
{ 
	if (st > dr) {
		printf("Tipul gramaticii: GFR\n"); 
		BEGIN(INITIAL); 
		print_alfabet();
		free_buffers();
		tip_gasit_gfr = true;
		exceptie_productie = false;
		caz_special = false;
		check_start_symbol = 0;
	}
	dr = 0;
}	
	YY_BREAK
/*la finalul liniei, este resetat st; la acest moment gramatica poate fi GDC sau GFR*/
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 404 "program.l"
{ 
	if (st > dr) {
		printf("Tipul gramaticii: GFR\n"); 
		BEGIN(INITIAL); 
		print_alfabet();
		free_buffers();
		tip_gasit_gfr = true;
		exceptie_productie = false;
		caz_special = false;
	check_start_symbol = 0;
	}
	st = 0; 
	dr = 0; 
	BEGIN(TIP_1_0_GRAMATICA_ST); 
}
	YY_BREAK
/*daca s-a ajuns la finalul definitiei gramaticii in acesta stare, gramatica este GDC*/
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 420 "program.l"
{ 
	/*daca a fost gasita productia S->e, se verifica numarul de aparitii al simbolului de start in partea dreapta a aproductiilor*/

	if (tip_gasit_gfr == false) {
		if (caz_special == false || ((caz_special == true) && (check_start_symbol == 0))) {
			printf("Tipul gramaticii: GDC\n");
			print_alfabet(); 
			free_buffers();
		}
		else if ((caz_special == true) && (check_start_symbol != 0)) {
			/*daca exista S->e si S apare in partea dreapta a unei productii, avem GFR*/
			printf("Tipul gramaticii: GFR\n");
			print_alfabet(); 
			free_buffers();
		}
	}
	tip_gasit_gfr = false;
	exceptie_productie = false;
	caz_special = false;
	check_start_symbol = 0;
	BEGIN(INITIAL); 
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 442 "program.l"
{ }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 444 "program.l"
{ }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 447 "program.l"
{ BEGIN(ALFABET_INTRARE_AS); printf("Alfabetul de intrare: {");  }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 448 "program.l"
{ printf("%s, ", yytext); } 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 449 "program.l"
{ yyless(1); printf("%s}\n", yytext); BEGIN(AUTOMAT); } 
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 450 "program.l"
{ BEGIN(AUTOMAT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 451 "program.l"
{ }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 453 "program.l"
{ BEGIN(NUMARARE_STARI); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 454 "program.l"
{ numarare_stari_as++; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 455 "program.l"
{ printf("Numarul de stari: %d\n", numarare_stari_as); 			
									  BEGIN(AUTOMAT); }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 457 "program.l"
{ }									  
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 460 "program.l"
{ printf("Starea initiala: "); BEGIN(STARE_INITIALA_AS); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 461 "program.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 462 "program.l"
{ BEGIN(AUTOMAT); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 463 "program.l"
{ }
	YY_BREAK
/*s-a identificat definitia starilor finale la AS*/
case 63:
YY_RULE_SETUP
#line 466 "program.l"
{ BEGIN(STARI_FINALE_AS); printf("Starile finale: {"); stari_finale = true; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 467 "program.l"
{ printf("%s, ", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 468 "program.l"
{ yyless(yyleng - 1); printf("%s}\n", yytext); BEGIN(AUTOMAT); } 
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 469 "program.l"
{ BEGIN(AUTOMAT); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 470 "program.l"
{ }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 472 "program.l"
{ BEGIN(ALFABET_STIVA); printf("Alfabetul stivei: {"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 473 "program.l"
{ printf("%s, ", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 474 "program.l"
{ yyless(yyleng - 1); printf("%s}\n", yytext); BEGIN(AUTOMAT); } 
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 475 "program.l"
{ BEGIN(AUTOMAT); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 476 "program.l"
{ }
	YY_BREAK
/*este identificat inceputul definirii functiilor de tranzitie, sirul pe care s-a facut match va fi reanalizat mai departe*/
case 73:
YY_RULE_SETUP
#line 479 "program.l"
{ BEGIN(DEFINIRE_TRANZITII); 
									  if (afisare_tranzitii == 0) {
									  	printf("Functia de tranzitie:\n");
									  	afisare_tranzitii = 1;
									  }  
									  yyless(0);
									}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 487 "program.l"
{ yyless(yyleng - 5); printf("\tm(%s, ", yytext); stare = strdup(yytext); BEGIN(TRANZITIE_AS);
									   copie_tranzitie1 = (char*)malloc(150 * sizeof(char)); 
									   sprintf(copie_tranzitie1, "\tm(%s, ", yytext); /*este memorat string-ul aferent tranzitiei curente*/
									 }
	YY_BREAK
/*regula care se aplica cand sunt definite mai multe tranzitii pentru aceeasi stare*/
case 75:
YY_RULE_SETUP
#line 492 "program.l"
{ printf("\tm(%s, ", stare); 
									  BEGIN(TRANZITIE_AS); yyless(0); }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 494 "program.l"
{ }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 495 "program.l"
{ yyless(yyleng - 2);
									  /*verifica daca simbolul analizat este varibila interna definitiei curente*/
									  if (verifica_variabila_interna(yytext) == 0) { /*simbolul nu este variabila interna*/
										  /*verifica daca simbolul analizat este variabila globala*/
										  if (verifica_variabila_globala(yytext) == 0) {
										  	printf("%s, ", yytext);
										  }
										  else { /*este afisata prima valoare pe care o are asociata variabila globala*/
										  	printf("%s, ", valori_variabile[prima_aparitie(yytext)][1]);
										  	variabila_tranzitie = strdup(yytext);
										  }
									  }
									  else {
									  	variabila_interna = true;
									  	printf("%s, ", valori_variabile_interne[prima_aparitie_interna(yytext)][1]);
										variabila_tranzitie = strdup(yytext);
									  }
									}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 513 "program.l"
{ yyless(yyleng - 3); printf("%s) = ", yytext); 
									  char* aux = (char*)malloc(100 * sizeof(char)); 
									  sprintf(aux, "%s) = ", yytext);
									  copie_tranzitie2 = strdup(aux);
									}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 518 "program.l"
{ yyless(yyleng - 4);
									  stiva = strdup(yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 520 "program.l"
{ yyless(yyleng - 4);
									  stiva = strdup(yytext); }	
	YY_BREAK
/*este identificata starea urmatoare dintr-o tranzitie*/	
/*s-a incheiat scrierea unei tranzitii*/								  								  	
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 524 "program.l"
{ yyless(yyleng - 3); 
									  printf("(%s, ", yytext); 
									  char* aux1 = (char*)malloc(100 * sizeof(char)); sprintf(aux1, "(%s, ", yytext);
									  copie_tranzitie2 = strcat(copie_tranzitie2, aux1);
									  printf("%s)\n", stiva); 
									  char* aux2 = (char*)malloc(100 * sizeof(char)); sprintf(aux2, "%s)\n", stiva);
									  copie_tranzitie2 = strcat(copie_tranzitie2, aux2);
									  int i;
	/*daca anterior s-a identificat o variabila care trebuie extinsa, vor fi afisate si tranzitiile coresp. celorlalte valori ale variabilei*/
									  if (variabila_tranzitie != NULL) {
									  	int i;
									  	/*prima valoare asociata a fost deja afisata la identificarea variabilei*/
									  	if (variabila_interna == false) {
										  	int first = -1;
										  	for (i = 0; i < nr_valori; i++) {
												if (strcmp(valori_variabile[i][0], variabila_tranzitie) == 0) {
													if (first == -1) {
														first = i;
													}
													if (i != first) {
														printf("%s%s, %s", copie_tranzitie1, valori_variabile[i][1], copie_tranzitie2);
													}
												}
											}
										}
										else { /*sunt afisate valorile asociate variabilei locale*/
											int first = -1;
										  	for (i = 0; i < nr_valori_interne; i++) {
												if (strcmp(valori_variabile_interne[i][0], variabila_tranzitie) == 0) {
													if (first == -1) {
														first = i;
													}
													if (i != first) {
														printf("%s%s, %s", copie_tranzitie1, valori_variabile_interne[i][1], copie_tranzitie2);
													}
												}
											}
										}
										variabila_interna = false;
									  	free(variabila_tranzitie);
									  	variabila_tranzitie = NULL;
									  }
									  BEGIN(DEFINIRE_TRANZITII); }
	YY_BREAK
/*este identificat finalul definitiei unei tranzitii*/
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 568 "program.l"
{ BEGIN(AUTOMAT); }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 569 "program.l"
{ }
	YY_BREAK
/*daca din oricare dintre stari se gaseste /*, trebuie sa ignoram tot continutul comentariului*/
case 84:
YY_RULE_SETUP
#line 572 "program.l"
{ int before_comment_state = YYSTATE;
							          yy_push_state(before_comment_state);
									  BEGIN(COMENTARIU); }
	YY_BREAK
/*igonora orice caracter de input pana la caracterul * */
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 576 "program.l"
{  }
	YY_BREAK
/*s-a identificat finalul comentariului si se revine la starea de dinainte de gasirea comentariului*/
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 578 "program.l"
{ yy_pop_state(); }
	YY_BREAK
/*s-a identificat finalul definitiei unui automat sau a unei gramatici*/
/*se verifica daca au fost definite starile finale*/
/*daca nu au fost define stari finale, se va afisa mesajul aferent cand multimea starilor finale este vida*/
case 87:
YY_RULE_SETUP
#line 582 "program.l"
{ if (afisare_automat == true && stari_finale == false) {
									  	printf("Starile finale: {}\n");
								      }
									  BEGIN(INITIAL); 
									  numarare_stari_as = 0; 
									  afisare_tranzitii = 0; 
									  stari_finale = false;
									  afisare_automat = false;
									  printf("\n"); 
									  /*trebuie sterse variabilele locale memorate pentru definitia curenta de automat/gramatica*/ 
									  if (valori_variabile_interne != NULL) {
									  	free_variabile_locale();
									  	free_valori_var_locale();
									  }
									 }
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 597 "program.l"
{ }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 600 "program.l"
ECHO;
	YY_BREAK
#line 2072 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(GRAMATICA):
case YY_STATE_EOF(AUTOMAT):
case YY_STATE_EOF(GASESTE_NUME):
case YY_STATE_EOF(COMENTARIU):
case YY_STATE_EOF(ALFABET_GRAMATICA):
case YY_STATE_EOF(NETERMINALI_GRAMATICA):
case YY_STATE_EOF(SIMBOL_START_GRAMATICA):
case YY_STATE_EOF(PRODUCTII_GRAMATICA):
case YY_STATE_EOF(ALFABET_INTRARE_AS):
case YY_STATE_EOF(ALFABET_STIVA):
case YY_STATE_EOF(STARE_INITIALA_AS):
case YY_STATE_EOF(STARI_FINALE_AS):
case YY_STATE_EOF(TRANZITIE_AS):
case YY_STATE_EOF(NUMARARE_STARI):
case YY_STATE_EOF(STIVA):
case YY_STATE_EOF(DEFINIRE_TRANZITII):
case YY_STATE_EOF(MEMORARE_VARIABILE):
case YY_STATE_EOF(MEMORARE_ALFABET_GRAMATICA):
case YY_STATE_EOF(MEMORARE_NETERMINALI):
case YY_STATE_EOF(MEMORARE_SIMBOL_START):
case YY_STATE_EOF(TIP_2_3_GRAMATICA):
case YY_STATE_EOF(TIP_2_1_GRAMATICA):
case YY_STATE_EOF(VERIFICA_TIP_3):
case YY_STATE_EOF(TIP_1_0_GRAMATICA_ST):
case YY_STATE_EOF(TIP_1_0_GRAMATICA_DR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 441 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 441 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 440);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 600 "program.l"


	/*analiza se face dintr-un singur fisier*/
int yywrap(){
	return(1);
}

int main(int argc, char** argv){
	yyin = fopen(argv[1], "r");
	yylex();
	
	/*
	printf("variabile globale: \n");
	int i;
	for (i = 0; i < nr_variabile; i++) {
		printf("%s ", variabile[i]);
	}
	printf("\nvalorile pentru variabilele gloabale: \n");
	
	for (i = 0; i < nr_valori; i++) {
		printf("%s %s\n", valori_variabile[i][0], valori_variabile[i][1]);
	}
	
	printf("variabile locale: \n");
	for (i = 0; i < nr_variabile_interne; i++) { 
		printf("%s ", variabile_interne[i]);
	}
	
	printf("\nvalorile pentru variabilele interne: \n");
	
	for (i = 0; i < nr_valori_interne; i++) {
		printf("%s %s\n", valori_variabile_interne[i][0], valori_variabile_interne[i][1]);
	}*/
	return 0;
}



















